[hooks]
pre-commit = "cargo test && cargo clippy --all-targets --all-features -- -D warnings && cargo fmt --all -- --check && cd arkworks_adapter && cargo test && cargo clippy --all-targets --all-features -- -D warnings && cargo fmt --all -- --check"

[logging]
verbose = true
